name: pre-commit-action

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-editor:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Clone repository
      uses: actions/checkout@v3 
      
    - name: install 
      run : pip install -r requirements.txt
      
    - name: blackcheck
      uses: jpetrucciani/black-check@master
      
    - name: isort
      uses: isort/isort-action@master
      with:
        requirementsFiles: "requirements.txt requirements-test.txt"

    - name: flake8
      uses: cclauss/Find-Python-syntax-errors-action@master